### ISSUE TITLE
Can't build on windows with any VS version I have

### ISSUE THREAD

**Issue by abdarhman** [cdcseacave/openMVS#121]
Hi,

I'm facing too many errors while building OpenMVS on windows, I solved many of them but there're alot remaining, some file I found are just for linux and not windows like mpfr.h which it self depends on gmp.h that's also for unix systems or just I can't install on windows.

If it's ok, can I get some detailed instructions of the dependencies, as it seems that as long as I solve a problem a new one emerge and I think it's a problem I had done in the beginning.

I also think we need to publish a more detailed instruction of how to build on windows, I checked the binaries available for windows.

Thanks in advance.

**Comment by cdcseacave** [comment]
Sorry for the problems you are facing. Indeed on Windows there is some more work to build all third party libraries, but once you do that, OpenMVS should build. mpfr.h and gmp.h are not linux only, but just some third party libraries needed for CGAL library. So in order to build CGAL just follow the CGAL build instruction on their website. Same procedure for all other third party libs, just follow the corresponding build instructions on their website.
