### ISSUE TITLE
open PLY file exported by openMVS in PCL

### ISSUE THREAD

**Issue by woshizja** [cdcseacave/openMVS#159]
I got the PLY file（mesh and texture） exported by openMVS，they are displayed correctly in MeshLab.
But when I load and show them in PCL, I just got a warning（no error）：

> [pcl::PLYReader] ...path_to_ply_scene_dence_mesh.ply:8: property 'list uint8 uint32 vertex_indices' of element 'face' is not handled

The PCLVisualizer viewer show nothing（no mesh， no cloud）. Code is：

```
/*******************read mesh*******************/
boost::shared_ptr<pcl::PolygonMesh> mesh;
mesh.reset(new pcl::PolygonMesh);

pcl::PLYReader plyreader;
plyreader.read(path_to_ply, *mesh);

viewer->addPolygonMesh(*mesh, "mesh"); 
```
The `cloud` part of `PolygonMesh` can be displayed correctly:
```
pcl::PolygonMesh mesh;
pcl::PLYReader plyreader;
plyreader.read(path_to_ply, mesh);

pcl::PointCloud<pcl::PointXYZ>  cloud;
pcl::fromPCLPointCloud2(mesh.cloud, cloud);
viewer->addPointCloud(cloud, "cloud");
```

Anyone open the output of openMVS in PCL successfully？
How to open texturemesh in PCL？
I also want to know：since a ply file can be a cloud， a mesh and texture，how to distinguish them？

**Comment by riyueshi** [comment]
I think this is more likely a problem of using PCL not openMVS, Maybe [this](http://www.dcs.ed.ac.uk/teaching/cs4/www/graphics/Web/ply.html) would be helpful for your last question. Since the ply file exported by openMVS can open by meshLab you can convert the ply file as you wanted(by "save as" function). If you had already opened a ply file successfully in PCL, you can check out the difference with the one exported by openMVS
