### ISSUE TITLE
Issue with running ./TextureMesh command

### ISSUE THREAD

**Issue by deusclovis** [cdcseacave/openMVS#168]
This is the output I have from running ./TextureMesh /statue_out/mvs/scene_dense_mesh.mvs

02:29:18 [App     ] Build date: Jan 11 2017, 18:59:32
02:29:18 [App     ] CPU: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
02:29:18 [App     ] RAM: 3.86GB Physical Memory 0B Virtual Memory
02:29:18 [App     ] OS: Linux 4.4.0-53-generic (x86_64)
02:29:18 [App     ] SSE & AVX compatible CPU & OS detected
02:29:18 [App     ] Command line: /statue_out/mvs/scene_dense_mesh.mvs

================
What could be the issue?

**Comment by jpwhitney** [comment]
It looks like you don't have enough memory.  From my experience and from following this project my understanding is that TextureMesh can require a large amount of RAM.

I noticed you are using Linux, you could add swap space to increase your machine's virtual memory.  I have had some success with this method using an SSD for the swapfile.  There is a good tutorial on the digitalocean website on how to add more swap space.

It appears that you have 0 bytes allocated for swap and only 3GB of RAM, I doubt this will be enough.  I've seen talk about making this step more friendly for small systems but not sure if any progress has been made.

Maybe PMVS/CMVS will work for you instead of OpenMVS.

**Comment by deusclovis** [comment]
Hmmm I used a 8GB droplet on digitalocean but it still shows me the same output. How much RAM is recommend to enable the meshification to work?

**Comment by jpwhitney** [comment]
It depends on the data set.  What is your data set like?  Can you share it?

**Comment by deusclovis** [comment]
Hi thanks for that.
I am trying to run it on this photoset:
https://github.com/deusclovis/statue

**Comment by jpwhitney** [comment]
What did you use to make the sparse point cloud?

I got some decent results, 39 out of 40 images calibrated with openMVG sequential using IMG_5048.jpg and IMG_5049.jpg as the initial pair.  Your camera exposure is all over the place and you don't have any images looking up at the chin of the statue so there are some odd parts there because of that.

Looks like about 6.5 GB of Vm is needed for the densifying the point cloud, a little over 10 GB for mesh reconstruction, nearly 23 GB for the refine mesh process, and then about 5 GB for texturing the mesh.

That is a very auspicious statue, but yeah it looks like you need some more RAM if you want to try openMVS with that dataset.  Have you tried CMVS-PMVS yet?

I shared the reconstruction with you:
http://www.filedropper.com/scenedensemeshreftexture
http://www.filedropper.com/scenedensemeshreftexture_1

**Comment by deusclovis** [comment]
Hi! thanks very much for that. I tried it on the biggest instance on DO and managed to run through the process! :D 

Amateur question -- How do I texture the mesh using the png file?

**Comment by jpwhitney** [comment]
Oh cool, that's a good option that you taught me about!

Just open the .ply with CloudCompare and if the .png is in the same folder it'll texture it.  Or do you mean the one you made?

Have you looked at the openMVS binary TextureMesh?  That's what I used.

**Comment by deusclovis** [comment]
mmmm i will try it later. But so far I am not able to texture the mesh in meshmixer or blender. No idea how to ..

**Comment by jpwhitney** [comment]
Sounds good, if it is not to do with openMVS perhaps you should close the issue.
