### ISSUE TITLE
can OpenMVS be used for commercial purposes?

### ISSUE THREAD

**Issue by pogilon** [cdcseacave/openMVS#268]
can OpenMVS be used for commercial purposes?

**Comment by cdcseacave** [comment]
OpenMVS is under AGPLv3 license. If you need more than that, pls contact me for details.

**Comment by cdcseacave** [comment]
I am not an expert in licenses, however the intent here is to encourage everyone to use it, but also to grow a community to improve and expand the library. And so the code is intended to be free even for commercial usage, with the condition that any modifications or additional modules that extend it to be made also open-source. However the results are far from my intent, as nobody have contributed to this library, and neither I know other open-source projects that employ OpenMVS.

If interested in contributing, there are many things I plan to add and improve, but due to lack of time I never have the chance.

**Comment by AndreaMonzini** [comment]
Thank you for the answer, even if i could use proprietary software i prefer to use free and open source projects like OpenMVS, Blender, GIMP, etc...

I'm not expert in licenses too but i like to read and study the licenses before to use the software and i wrote just to help to understand together the correct usage of OpenMVS under the AGPL license and specify that the output ( like the input ) should be not under AGPL and therefore this information can encourage more people to use OpenMVS instead of proprietary software.

The same happen with other GPL software like Blender and GIMP where the output (3D, 2D images)  is not under GPL.

Of course like you wrote any modification of the code or additional modules should be shared as open source code (with the same AGPL license ) to improve the library and the community collaboration.

About contributing i was planning to use Zenity in Linux for a GUI to manage OpenMVG and OpenMVS script to improve usability and encourage more people to use it.  Of course i will share it once done.

Do you plan to use Liberapay or Patreon? 

Thank you.

**Comment by cdcseacave** [comment]
Any GUI, even for linux only, is important. Congrats for the initiative.

A GUI was always in my plans, but as you can well see it never materialized. My vision is to create a cross platform GUI, directly in OpenGL, on top of the Viewer app already existent in OpenMVS, using something like: https://github.com/vurtun/nuklear

Even though that should be fairly easy, I will not find time for it in the near future.

No, I do not plat to use those platforms, and I am not looking for donations, thank you!

**Comment by ducha-aiki** [comment]
@cdcseacave Necro-posting, probably, but anyway :) 
As far as I can see will OpenCV, PyTorch, COLMAP, etc - MIT/Apache2 are much more  " encourage everyone to use it, but also to grow a community to improve and expand the library".

**Comment by cdcseacave** [comment]
The examples you gave are projects supported by big companies/institutions. OpenMVS is a project done in my own free time. I spent a huge amount of time making this project production ready in both quality and stability, without asking anything in return from anyone. AGPL is not restrictive if used as open source, it only requires that closed source usage obtains a license. Is that so much to ask?

**Comment by ducha-aiki** [comment]
@cdcseacave if you are taking this personal, so do I (no offence). 
kornia - is a project, which made by Edgar Riba, Jian Shi, me and our contributors. 
https://github.com/kornia/kornia/tree/master/kornia 
I don't think it is smaller or takes less time. 

In the same time, I can use it for whatever I do (including working for university or company).
