### ISSUE TITLE
error: unknown image format

### ISSUE THREAD

**Issue by 945540968** [cdcseacave/openMVS#271]
We used openMVG to run SFM, and transformed its output into openMVS.
But we have met a problem as following:
![pic](https://user-images.githubusercontent.com/33658092/33070705-e268be40-cef3-11e7-92eb-326d2be00480.png)
I saw there are some similar problems in the "issues"，but i still can't find a way to solve it. Can anybody help me? I will be very grateful.

**Comment by cdcseacave** [comment]
It seems like OpenMVS was not compiled with JPEG support. Make sure you point CMake to the JPEG library during OpenMVS configuration.

**Comment by 945540968** [comment]
Thanks,i will try.

**Comment by 945540968** [comment]
Thanks for your solution, but why i can't find the "JPEG" choice in cmake? How to point cmake to the JPEG library?

**Comment by Jessicayanyan** [comment]
In fact,I can't find the jpeg library during OpenMVS configuration,either.So I have trapped by this problem for a week.I will be very grateful if you can offer a more detailed answer!!

**Comment by NextDesign1** [comment]
Is JPEG_INCLUDE_DIR and JPEG_LIBRARY defined in your CMakeCache?

**Comment by antonyscerri** [comment]
This may not be the exact issue raised my the OP but there is a problem with the code only recognising .jpg and not.jpeg extensions which was the reason i was getting a bunch of different errors. libs/IO/Image.cpp just needs a small change to recognise both file extensions.

I cross posted a similar response to one of the other open issues related to similar errors which may have been caused by this specific problem.
