### ISSUE TITLE
Problem with orthophoto generation

### ISSUE THREAD

**Issue by kahlan78** [cdcseacave/openMVS#281]
Hi,
I'm trying to generate the orthophoto using TextureMesh.exe.
The scene_texture_mesh.ply is attached in the following (seems correct) but the orthophoto (also in attachament) is quite all black.
Any ideas?

scene_texture_mesh.ply:
![09d5b779f1f197226240778d232ae4ec5e011d77fcf7161815 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/34540802/34295654-c6cd1a7c-e70e-11e7-980b-90d5c54ab3df.jpg)

Orthophoto:
![scene_texture_mesh_orthomap](https://user-images.githubusercontent.com/34540802/34295633-ae0dcfae-e70e-11e7-93ff-9d486a245423.png)

Tks!

**Comment by cdcseacave** [comment]
ortho works only if the scene is properly oriented (+z is up), and the scene coordinates are in a manageable range (not georeferenced in crazy large coordinates)

**Comment by kahlan78** [comment]
Hi, 
the used images are not georeferenced. How can i be sure that the scene is properly oriented? Can i force the requsted orientation?
Tks!

**Comment by cdcseacave** [comment]
the proper orientation comes from geo-referencing it, with the mention that the final scene should be moved such that the center of the scene is 0 (in order to have manageable coordinates)

**Comment by kahlan78** [comment]
So, if i use georeferenced images (i.e. gps coordinate in the exif), the problem is automatically fixed?
Otherwise what are the proper steps in order to obtain the proper orientation?
Tks!

**Comment by cdcseacave** [comment]
depends on what you use to do the SfM, the SfM step georeference the scene

**Comment by kahlan78** [comment]
Hi,
many thanks for your answer. 
I fixed the sfm step of the openmvg pipeline as you can see here: https://github.com/openMVG/openMVG/issues/1206
Now i can see the orthomap, but still it has a wrong rotation. The scene coordinates are in a manageable range but the scene is not properly oriented as you can see in the following image:

![scene_dense_mesh_refine_texture_orthomap](https://user-images.githubusercontent.com/34540802/34980518-17ceb148-faa5-11e7-8cf3-e2f9c4507c6c.png)

It looks like the point of view for the orthomap generation is not nadir. I would like that the orthomap is oriented like this one:
![immagine](https://user-images.githubusercontent.com/34540802/34980587-454644f6-faa5-11e7-962d-8955460a187d.png)

How can i rotate the scene so to obtain the correct orthomap?
Thanks!

**Comment by cdcseacave** [comment]
As I was saying, anything related to orientation is the responsability the SfM step. There is nothing that can be done at the MVS step.

**Comment by kahlan78** [comment]
Thank you so much for responding so quickly!

I also have another question. If i compare the point cloud of the openmvg and the output of the densifypointcloud.exe step, it is clear that a lot of areas are missing as you can see here:
![immagine](https://user-images.githubusercontent.com/34540802/34983990-9f5ab85a-faaf-11e7-9345-6f36087ca74a.png)

Is there any advanced parameter that i can modify to cover all the area identified by openmvg? The problem is mostly on the area borders. Tks!

**Comment by cdcseacave** [comment]
u can try using `--number-views-fuse 2` for `DensifyPointCloud`, thought the reconstruction may be more noisy

**Comment by kahlan78** [comment]
the results that you see are already obtained with the following command line:

> %oMVS%\DensifyPointCloud.exe %workDir%\scene.mvs --number-views 0 --estimate-normals 1 --number-views-fuse 2 --resolution-level 1

the question refers to the hidden parameters

**Comment by fengyunxuan6** [comment]
I saw you could obtain a successful correct orthophoto. I have no clue in this regard. Would you mind share your pipeline with me? I will wait for your good news. Thanks very much.

**Comment by jpwhitney** [comment]
yes, https://docs.opendronemap.org/dataset.html#outputs

**Comment by fengyunxuan6** [comment]
@jpwhitney thanks. Does ODM need a GCP file?

**Comment by jpwhitney** [comment]
Not sure why you're asking me so many questions about ODM. You should probably learn how to use ODM from their docs or their github, not from an openMVS issue. This issue has not been resolved here as there seems to be no incentive here to have openMVS used as a tool to generate orthophotos or DEM's.

I merely suggested the use of ODM as I had some previous experience with trying to use openMVG + openMVS to create orthophotos and DEM's without success (similar to your problem), and had found ODM to be a useful alternative, giving results similar to Pix4D.

To continue further on the capabilities of ODM is beyond the scope of this issue and is more appropriate to be asked on the ODM forums or github project page.

If you can code the missing links it seems that openMVG + openMVS can be used to create orthophotos and DEM's. But for many reasons there has not been an effort by the community or creators to add such a capability to the open source side of this project so that non-programmers can use these tools to create these products (DEM's and orthophotos) or create georeferenced meshes. ODM seems to be a convenient alternative open source project that does provide a complete pipeline to resolve the issues mentioned here in this issue.

All the best.

**Comment by cdcseacave** [comment]
Thx @jpwhitney , that is exactly the point, even if OpenMVS is able to generate orthos and DEMs out of the box, it is not documented, and the reason for it is cause the that is not the purpose of this library. This library is trying to reconstruct a 3D scene as accurate/fast as possible. Whatever you do with the reconstruction after that is a totally different story. Any such story, ex ortho generation, becomes very complex if you want to support all possible scenarios and features, and such the project will quickly deviate from the main purpose. This project will never officially support ortho generation or document how to do it.
