### ISSUE TITLE
using silhouette masks to clip unwanted points

### ISSUE THREAD

**Issue by lulu1315** [cdcseacave/openMVS#36]
hello.I just started using openMVS and have excellent results so far.kudos for that.
are you planning to add the ability to use bitmaps masks to remove unwanted points from the reconstruction ?(maybe during DensifyPointCloud or Reconstructmesh).
Thanks
luc

**Comment by cdcseacave** [comment]
That would be quite easy to add, but unnecessary in my opinion. Can you
send me an example that would benefit from this?

**Comment by lulu1315** [comment]
sure.I attached a picture of the densecloud result.a lot of noise from the background that (I think) could be removed with masks.
the final mesh (texture is strange , first time I upload on sketchfab..) : https://skfb.ly/IDMz
![densecloud](https://cloud.githubusercontent.com/assets/13677315/11272762/8a1dacc0-8ecf-11e5-81bf-be35931969bc.jpg)

**Comment by cdcseacave** [comment]
The entire reconstruction looks strange. Could u share the photos to have a
look?

**Comment by ORNis** [comment]
Maybe my two cents...
Outliers from bg will be removed by visibility constraints used in ReconstructMesh. the last outliers can be removed manually in the resulting mesh with meshlab. Then you can use something like --input-mesh cleanedMesh.ply in other modules.

**Comment by lulu1315** [comment]
@ORNis : sure it can be removed by hands but it's so easier to draw masks to define what you want to keep
@cdcseacave : I did a global reconstruction with openMVG and the dense mesh is generated at resolution 0 (--resolution-level 0)
links to pictures : https://www.dropbox.com/s/sfi48y54xb9aos0/originales.zip?dl=0
link to openMVG json : https://www.dropbox.com/s/5ijdrlslwhymcp8/sfm_data.json?dl=0

**Comment by cdcseacave** [comment]
Romain is using this library for some time now, and he know how this works. The dense point-cloud is just a step in the entire path to the final goal: mesh. It might be noisy, but the mesh reconstruction will take care of that. The problems with this dataset are: first the photos are way over exposed, second, there no photos from  all around the object, and that is why some noise still survives the mesh reconstruction (there are not visibility checks to be done). Plus you seem to have done something wrong along the way, case I reconstructed from the images you sent me with all default parameters and it looks much better: https://skfb.ly/IDV8

So the short answer to your original question: No, OpenMVS will never support mask. Long answer, if at some point some kind of masks prove to be useful (which I doubt), these masks need to be algorithmically and automatically constructed. For example in this case, the background sky can be easily removed automatically, especially because it is so over exposed.

I appreciate your thoughts on this and for using the library.

**Comment by lulu1315** [comment]
ok thanks for your time.I didn't want to hurt anyone's feelings.
just for your info this ugly statue commemorates the brave resistance fighters who rose against the Tisoite clerico-fascists and the German Nazis in Bratislava.but I guess you talked about my pictures :)
cheers

**Comment by cdcseacave** [comment]
Sorry for letting you the wrong impression, I appreciate your input and I value it. I have however the bad habit of saying straight in the face what I think, even though never bad intended. And this time I was speaking about the statue, it might be for a noble cause, but it really ugly.

**Comment by lulu1315** [comment]
no problem.I used these (old) pictures because mve and cmvs gives me very bad results and I must admit that the result I had with your software are really impressive.I'm usually building a visual hull from masks and cameras parameters to clip the final result.I thought maybe it could be incorporated in your process.Cheers.luc
