### ISSUE TITLE
Any function to compute 3D world coordinates with pixel coordinates and depth?

### ISSUE THREAD

**Issue by squashking** [cdcseacave/openMVS#387]
Hi, I'm just wondering if there is any function that I can call to compute the 3D coordinates of a pixel with given depth or _z_ coordinate. Say, the pixel coordinate is (X, Y) in pixels, and the depth is _d_ meters, how to compute its corresponding 3D world coordinates (x,y,z) in meters?
I tried _camera.TransformPointI2W(Point3(X,Y,d))_;  but it does not seem to give the right result. Maybe I passed wrong values (e.g., different units) or misunderstood something.
Any answers would be appreciated!

**Comment by squashking** [comment]
@cdcseacave Could you shed some light? Many thanks!

**Comment by cdcseacave** [comment]
the function you tried and the way u used the params is correct (only mistake is of notation, usually the 3D coordinates are in capital letters)

so if u do not get the expected result, the problem is either `d` or the assumptions you make about the units (maybe the scene u use was not scaled to meters)

**Comment by squashking** [comment]
@cdcseacave Thank you! I have figured out the reason. It seems the original images are downsized by 1/2 when OpenMVS does dense reconstruction. This can be seen from the estimated K matrix of each camera. So when computing the 3D coordinates, I need to make sure the image coordinates are scaled to 50%.
