### ISSUE TITLE
DensifyPointCloud crashes when -w (working folder) argument is used

### ISSUE THREAD

**Issue by rennu** [cdcseacave/openMVS#445]
### Specifications like the version of the project, operating system, and hardware

* Current master
* Ubuntu 16.04 with updates
* Xeon E3-1246v3, 32GB

### Steps to reproduce the problem

When running DensifyPointCloud use -w argument ie. ```DensifyPointCloud scene.mvs -w /datasets/mvs```

<img width="786" alt="openmvs" src="https://user-images.githubusercontent.com/2362509/59582965-8c28bf00-90e2-11e9-93d5-49ab92b87a07.png">

The breaking change was introduced in [this commit](https://github.com/cdcseacave/openMVS/commit/e017ff346ff2c809466445ee229ee00ed34a257e).

Test material:
[scene.mvs.zip](https://github.com/cdcseacave/openMVS/files/3295489/scene.mvs.zip)
[imgs.zip](https://github.com/cdcseacave/openMVS/files/3295490/imgs.zip)

**Comment by csparker247** [comment]
I've been running into this, too. The error seems to be rooted in the initialization of the dense config options. There's an empty string that probably shouldn't be empty (explanation below). A quick fix is to run the program with the `--dense-config-file` flag:
```Shell
DensifyPointCloud scene.mvs -w /datasets/mvs --dense-config-file densifier.cfg
```

#### Explanation
DensifyPointCloud tries to load the densifier configuration from a file at path `OPT::strDenseConfigFileName`. By default, this is an empty string. If the working directory option is not specified, this config path is left empty, and the attempt to load the file fails gracefully because the path is empty. 

However, if working directory _is_ specified, the config file path is set to `working + strDenseConfigFileName`, which is effectively just the path to the working directory. As a result, the config loader opens the _file descriptor for the working directory_, tries to read config information from it, and fails because it encounters some information that's too large to store in a string. This leads to the `std::length_error` exception.

I imagine this has been a bug for awhile, but only recently became a fatal one because of the addition of these lines:
https://github.com/cdcseacave/openMVS/blob/1f1cf6f7d02c739fe891a6d4ca42df63891937e8/apps/DensifyPointCloud/DensifyPointCloud.cpp#L169-L171
The `MAKE_PATH` macro is the one that's concatenating the working directory with the empty string. Prior to #422, `OPT::strDenseConfigFileName` would just be left empty.

**Comment by csparker247** [comment]
Actually, the more I look into it, this only masks the problem. There's a whole range of things that fail to load because of the `MAKE_PATH` macro appends the working directory onto most paths. From what I can tell, specifying the working directory is only useful if the paths in `scene.mvs` are relative to a folder that is different from your current directory.

**Comment by cdcseacave** [comment]
by default the working folder is the folder where the command is called (as far as I know that is true on both windows and linux); so specifying the working directory is only useful if scene.mvs (so the MVS project and all its files) are not at the current directory; in that case instead of writing absolute paths to all argument, you only specify the working path once and all commands are relative to the working folder

**Comment by csparker247** [comment]
@cdcseacave That is very clarifying. Thank you! So paths in the scene file should _always_ be relative to the location of the scene file? Given this, I see some bugs related to fairly normal use cases that need to be addressed, but I will open another issue for those.

For the `DensifyPointCloud` exception, `strDenseConfigFileName` I think should be given a default value OR there needs to be some logic around detecting whether it is empty _before_ appending the working directory and trying to load/save a dense config.

Additionally, it might be good if something in the `SML::Load` call sequence checks whether the path is a real file or a directory. This one is kind of optional, but might save some headache later.

I don't want to just helicopter in, point out bugs, and leave. I'm very happy to contribute PRs for these issues. Just let me know how you would like to approach solving them.

**Comment by cdcseacave** [comment]
feel free to make PR for the bugs you found
