### ISSUE TITLE
Using GPS priors in OpenMVG causing quantization in OpenMVS

### ISSUE THREAD

**Issue by joel7t** [cdcseacave/openMVS#589]
### Describe the bug
I am using the OpenMVG to OpenMVS pipeline.  The images that I am using for my 3D reconstruction have GPS Exif tags.  The Exif tags are specified in LLA (Latitude, Longitude, Altitude).  I am using `-P` during both `openMVG_main_SfMInit_ImageListing` and `openMVG_main_GlobalSfM`, resulting in a sparse point cloud that lines up with my GPS coordinates.

When OpenMVG reads the GPS data from the Exif tag, it converts the LLA coordinates to a cartesian coordinate system, either UTM (Universal Transverse Mercator) or ECEF (Earth-Centered, Earth-Fixed).  I am currently using UTM and one of the resulting cartesian coordinates is very large, around 4,000,000.

When I feed the sparse point cloud from OpenMVG through Densify Point Cloud in OpenMVS, the dense point cloud ends up with _layers/slices_.  The points end up on parallel planes that are not a part of my 3D reconstruction, and the space between the planes does not have any points.  For instance a wall that should be a flat surface of points ends up looking like the slats of a very large vent.  This causes a lot of problems for the rest of the pipeline (mesh, refinement, texturing), resulting in a 3D reconstruction that isn't useful.

### Expected Behaviour
I expect the 3D reconstruction when using GPS priors to be very similar (nearly identical) to the 3D construction obtained without GPS priors.

### Additional Context
I am able to build my 3D reconstruction without GPS priors and it produces a dense point cloud that doesn’t have the unexpected layers/slices that I describe above.  I have also tried using ECEF instead of UTM, however it makes the problem worse because all three coordinates are very large.

In the coordinates in the PLY files, the output of OpenMVG are stored as doubles, while the output of Densify Point Cloud from OpenMVS are stored as floats.  It also looks like the point cloud is represented internally by a float in OpenMVS.  For the values around 4 million, single floating point values would not provide enough detail to resolve the smaller details in my 3D reconstruction, which would explain the layer/slice effect I’m seeing in my densified point cloud.

### Questions
**First question**: Is this quantization, or is it some other effect?

**Second question**: If this is quantization, then is there a different workflow for using GPS priors that avoids this problem?

**Comment by cdcseacave** [comment]
Hey Joel!

This issue was discussed several times already. Processing anything stored in absolute coordinates will give you all kinds of problems; even simple additions and multiplications will end up in huge errors, due to the limited floating precision. While parts of OpenMVS uses doubles for sensitive computations, most of the code uses floats as a speed compromise. (in fact I think even if all code would use doubles, it will still be suffering of big errors)

In order to process scenes in absolute coordinates, the input should be normalized before processing (in your case I suggest to convert it to ENU) and transformed back to absolute coordinates at the end of the reconstruction, and that is the responsibility of the user. For this purpose the MVS interface presents the [transform](https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/Interface.h#L586) member, in order to be able to close the loop at the end without storing separately the normalization transform.

**Comment by joel7t** [comment]
Hi,

Thanks for all the information in your response, that's really good to know!  My apologies for not finding the previous discussions on this topic; my google-fu failed me.

To normalize my 3D reconstruction as you suggested, I have found `openMVG_main_ChangeLocalOrigin` in OpenMVG, which translates the 3D reconstruction to a new origin and saves the translation to a text file.  I am applying the translation just before step #9 of `MvgMvsPipeline.py`.  Because I'm starting with UTM, this seems like it's essentially converting my reconstruction to ENU.  Is that correct?

Thanks for your help and thanks for the great tool!

Joel

**Comment by cdcseacave** [comment]
:)
I do not know this particular tool in OpenMVG, but it does not matter much in what coordinate system it is when you export it to OpenMVS, as long as the points have normal ranges for float32 precision, and as long as you know to apply the back transform after OpenMVS is done.
