### ISSUE TITLE
How to use TextureMesh from rgbd pictures and extrinsic？

### ISSUE THREAD

**Issue by zmf2022** [cdcseacave/openMVS#883]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cdcseacave** [comment]
thx for the details

**Comment by zmf2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，已收到您的邮件，将尽快给您回复！

**Comment by Yes-Jumby** [comment]
so how to do it?

**Comment by cdcseacave** [comment]
now that you added details, I can point you to use the `Interface.h` to both create a MVS scene and DMAP depth-maps with your data, and from that point just use the normal OpenMVS pipeline

**Comment by Yes-Jumby** [comment]
> 

what i have :I have extrinsic and intrinsic and rgb and depth images（dense，from openmvs），and the pair of views form colmap.
note: i donot have sparse points.
what i have done: i have used the Interface.h to both create a MVS scene and DMAP depth-maps with my data,but when i use 
DensifyPointCloud scene.mvs --resolution-level 0 --number-views 10
then ,i get those error messages ,after i read the source code ,i think it is caused by sparse points missing.@cdcseacave


 F:\data> DensifyPointCloud scene.mvs --resolution-level 0 --number-views 10
19:36:58 [App     ] Build date: Apr 17 2022, 11:49:17
19:36:58 [App     ] CPU: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 cores)
19:36:58 [App     ] RAM: 15.87GB Physical Memory 128.00TB Virtual Memory
19:36:58 [App     ] OS: Windows 8 x64
19:36:58 [App     ] Disk: 346.13GB (465.75GB) space
19:36:58 [App     ] SSE & AVX compatible CPU & OS detected
19:36:58 [App     ] Command line: DensifyPointCloud scene.mvs --resolution-level 0 --number-views 10
19:36:58 [App     ] CUDA device 0 initialized: NVIDIA GeForce RTX 2060 (compute capability 7.5; memory 6.00GB)
19:36:58 [App     ] Camera model loaded: platform 0; camera  0; f 0.737x0.737; poses 64
19:36:58 [App     ] Scene loaded from interface format (3ms):
        64 images (64 calibrated) with a total of 27.00 MPixels (0.42 MPixels/image)
        10 points, 0 vertices, 0 faces
19:36:58 [App     ] Preparing images for dense reconstruction completed: 64 images (33ms)
19:36:58 [App     ] error: reference image  27 has not enough images in view
19:36:58 [App     ] error: reference image  31 has not enough images in view
19:36:58 [App     ] error: reference image  23 has not enough images in view
19:36:58 [App     ] error: reference image  63 has not enough images in view
19:36:58 [App     ] error: reference image  34 has not enough images in view
19:36:58 [App     ] error: reference image  54 has not enough images in view
19:36:58 [App     ] error: reference image  46 has not enough images in view
19:36:58 [App     ] error: reference image  38 has not enough images in view
19:36:58 [App     ] error: reference image  41 has not enough images in view
19:36:58 [App     ] error: reference image  13 has not enough images in view
19:36:58 [App     ] error: reference image  29 has not enough images in view
19:36:58 [App     ] error: reference image  37 has not enough images in view
19:36:58 [App     ] error: reference image  44 has not enough images in view
19:36:58 [App     ] error: reference image  56 has not enough images in view
19:36:58 [App     ] error: reference image  12 has not enough images in view
19:36:58 [App     ] error: reference image  60 has not enough images in view
19:36:58 [App     ] error: reference image  14 has not enough images in view
19:36:58 [App     ] error: reference image  62 has not enough images in view
19:36:58 [App     ] error: reference image  30 has not enough images in view
19:36:58 [App     ] error: reference image  26 has not enough images in view
19:36:58 [App     ] error: reference image   6 has not enough images in view
19:36:58 [App     ] error: reference image  58 has not enough images in view
19:36:58 [App     ] error: reference image  50 has not enough images in view
19:36:58 [App     ] error: reference image  18 has not enough images in view
19:36:58 [App     ] error: reference image  42 has not enough images in view
19:36:58 [App     ] error: reference image  10 has not enough images in view
19:36:58 [App     ] error: reference image   2 has not enough images in view
19:36:58 [App     ] error: reference image  22 has not enough images in view
19:36:58 [App     ] error: reference image  28 has not enough images in view
19:36:58 [App     ] error: reference image  16 has not enough images in view
19:36:58 [App     ] error: reference image  20 has not enough images in view
19:36:58 [App     ] error: reference image  32 has not enough images in view
19:36:58 [App     ] error: reference image  43 has not enough images in view
19:36:58 [App     ] error: reference image  19 has not enough images in view
19:36:58 [App     ] error: reference image  35 has not enough images in view
19:36:58 [App     ] error: reference image  55 has not enough images in view
19:36:58 [App     ] error: reference image  33 has not enough images in view
19:36:58 [App     ] error: reference image  15 has not enough images in view
19:36:58 [App     ] error: reference image  21 has not enough images in view
19:36:58 [App     ] error: reference image  53 has not enough images in view
19:36:58 [App     ] error: reference image  61 has not enough images in view
19:36:58 [App     ] error: reference image  25 has not enough images in view
19:36:58 [App     ] error: reference image   7 has not enough images in view
19:36:58 [App     ] error: reference image  59 has not enough images in view
19:36:58 [App     ] error: reference image  39 has not enough images in view
19:36:58 [App     ] error: reference image  51 has not enough images in view
19:36:58 [App     ] error: reference image  24 has not enough images in view
19:36:58 [App     ] error: reference image  48 has not enough images in view
19:36:58 [App     ] error: reference image   4 has not enough images in view
19:36:58 [App     ] error: reference image  40 has not enough images in view
19:36:58 [App     ] error: reference image   0 has not enough images in view
19:36:58 [App     ] error: reference image  17 has not enough images in view
19:36:58 [App     ] error: reference image  57 has not enough images in view
19:36:58 [App     ] error: reference image   5 has not enough images in view
19:36:58 [App     ] error: reference image  49 has not enough images in view
19:36:58 [App     ] error: reference image   9 has not enough images in view
19:36:58 [App     ] error: reference image   1 has not enough images in view
19:36:58 [App     ] error: reference image  45 has not enough images in view
19:36:58 [App     ] error: reference image  47 has not enough images in view
19:36:58 [App     ] error: reference image  36 has not enough images in view
19:36:58 [App     ] error: reference image   3 has not enough images in view
19:36:58 [App     ] error: reference image   8 has not enough images in view
19:36:58 [App     ] error: reference image  11 has not enough images in view
19:36:58 [App     ] error: reference image  52 has not enough images in view
19:36:58 [App     ] Selecting images for dense reconstruction completed: 0 images (16ms)
Fused depth-maps 0 (100%, 0ms)
19:36:58 [App     ] Depth-maps fused and filtered: 0 depth-maps, 0 depths, 0 points (-2147483648%) (0ms)
19:36:58 [App     ] Densifying point-cloud completed: 0 points (52ms)
19:36:58 [App     ] Scene saved (3ms):
        64 images (64 calibrated)
        0 points, 0 vertices, 0 faces
19:36:58 [App     ] MEMORYINFO: {
19:36:58 [App     ]     PageFaultCount 48842
19:36:58 [App     ]     PeakWorkingSetSize 185.83MB
19:36:58 [App     ]     WorkingSetSize 185.71MB
19:36:58 [App     ]     QuotaPeakPagedPoolUsage 419.04KB
19:36:58 [App     ]     QuotaPagedPoolUsage 419.04KB
19:36:58 [App     ]     QuotaPeakNonPagedPoolUsage 34.10KB
19:36:58 [App     ]     QuotaNonPagedPoolUsage 33.71KB
19:36:58 [App     ]     PagefileUsage 267.36MB
19:36:58 [App     ]     PeakPagefileUsage 268.67MB
19:36:58 [App     ] } ENDINFO

**Comment by GraphOpti** [comment]
> now that you added details, I can point you to use the `Interface.h` to both create a MVS scene and DMAP depth-maps with your data, and from that point just use the normal OpenMVS pipeline

Hello, I recently work on implementing the OpenMVS to handle RGBD data. I did create the scene file(scene.mvs) for my data and convert the depth data into dmap. While I do not understand how OpenMVS read my dmap files. If I run DensifyPointCloud, it regenerate the dmap with the default MVS algoritms. So what should I do to reconstruct a textured model after create the scene file and dmap files?
